language: node_js
node_js:
  - "8"
cache: yarn


# Use macOS 10.12: https://docs.travis-ci.com/user/languages/objective-c/
matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode9.1
      env: TEST_SUITE=test-build
    - os: linux
      dist: trusty
      env: TEST_SUITE=lint
    - os: linux
      dist: trusty
      env: TEST_SUITE=test-build

before_install:
  - curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
      tar xzf nvim-macos.tar.gz
      export PATH="${PATH}:node_modules/.bin:${PWD}/nvim-osx64/bin"
    else
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
      tar xzf nvim-linux64.tar.gz
      export PATH="${PATH}:node_modules/.bin:${PWD}/nvim-linux64/bin"
    fi
  - echo "${PATH}"
  - nvim --version

install:
  - yarn install

script:
  - export NODE_ENV=test
  - yarn global add codecov
  - yarn global add typescript
  - yarn run $TEST_SUITE

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: never
    on_cancel: never
    on_error: never
