let $NODE_ENV='test'
set nocompatible

set hidden
set noswapfile
set nobackup
set completeopt=menuone,noinsert,noselect
set tabstop=2
set cmdheight=2
set updatetime=300
set et
set noshowmode

let s:dir = expand('<sfile>:h')
let s:root = expand('<sfile>:h:h:h')
let s:plugin = s:dir.'/plugins'

autocmd BufNewFile,BufRead *.ts  set filetype=typescript

imap <silent> <C-x><C-u> <Plug>(coc-complete-custom)

execute 'set runtimepath+='.s:root
execute 'set runtimepath+='.s:plugin

function! SetDictionary()
  exe 'setl dictionary+='.s:dir.'/test.dict'
endfunction

autocmd FileType vim setlocal omnifunc=syntaxcomplete#Complete
exe 'setl tags+='.s:dir.'/tags'

