set nocompatible

set hidden
set noswapfile
set nobackup
set completeopt=menuone,noinsert,noselect
set tabstop=2
set cmdheight=2
set shiftwidth=2
set updatetime=300
set expandtab
set noshowmode
set shortmess=at

let s:dir = expand('<sfile>:h')
let s:root = expand('<sfile>:h:h:h')
let g:coc_node_env = 'test'

let g:coc_vim_commands = [{
  \ "id": "config",
  \ "cmd": "edit coc-settings.json"
  \ }]

autocmd BufNewFile,BufRead *.ts  set filetype=typescript

execute 'set runtimepath+='.s:root
