let $NODE_ENV='test'
set nocompatible

set noswapfile
set nobackup
set completeopt=menuone,noinsert,noselect

let s:root = expand('<sfile>:h:h:h')

autocmd BufNewFile,BufRead *.ts  set filetype=typescript
execute 'set runtimepath+='.s:root
