name: Publish Release Task

on:
  schedule:
    - cron: '0 16 * * *'  # UTC时间16:00（对应北京时间+8时区的0点）

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install pynvim

      - name: Setup vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: v9.0.0815

      - name: Setup neovim
        id: nvim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install Dependencies
        env:
          VIM_COMMAND: ${{ steps.vim.outputs.executable }}
          NVIM_COMMAND: ${{ steps.nvim.outputs.executable }}
        run: |
          npm i -g bytes
          npm ci
          NODE_ENV=production node esbuild.js
          sudo apt-get install -y ripgrep exuberant-ctags
          rg --version
          ctags --version
          vim --version
          nvim --version

      - name: Execute release.sh
        run: |
          chmod +x ./release.sh
          ./release.sh
